---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
  - "client/**/*.jsx"

exclude_patterns:
  - "webpack.config.*.js"
  - "client/config/firebase.js"


exclude_paths:
  - "node_modules/"
  - "client/__mocks__/"
  - "template/*"
  - "server/test"
  - "client/tests"
  - "server/migrations"
  - "server/models"
