env:
  global:
    - CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
language: node_js
node_js:
  - "6.10.0"
env:
  - NODE_ENV=test

cache:
  directories:
  - "node_modules"

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN

script:
  - npm run test

services:
  - postgresql

before_script:
  - npm run build:client:dev
  - createuser william -s -U postgres
  - createdb more-recipes_test --username=william
  - sequelize db:migrate

after_success: npm run coverage
