env:
  global:
    - CC_TEST_REPORTER_ID: "e895d45cfaffba8fb9a9fb36c8b3175563b0292e639308921059da19bf4fc5d2"
language: node_js
node_js:
  - "6.10.0"
env:
  - NODE_ENV=test

cache:
  directories:
  - "node_modules"

addons:
  code_climate:
    repo_token: "e895d45cfaffba8fb9a9fb36c8b3175563b0292e639308921059da19bf4fc5d2"

script:
  - npm run test

services:
  - postgresql

before_script:
  - createuser william -s -U postgres
  - createdb more-recipes_test --username=william
  - sequelize db:migrate

after_success: npm run coverage
