language: node_js
node_js:
  - "6"
env:
  - NODE_ENV=test

cache:
  directories:
  - "node_modules"

services:
  - postgresql

before_script:
  - createuser more-recipes -s -U postgres
  - createdb more-recipes_test --username=more-recipes
  - sequelize db:migrate

after_script: npm run coverage
