export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const REMOVE_AUTH_ERROR_MESSAGE = 'REMOVE_AUTH_ERROR_MESSAGE';

// FOR API CALLS
export const SET_FETCHING = 'SET_FETCHING';
// note: doesn't mean its successful just that the api responded
export const UNSET_FETCHING = 'UNSET_FETCHING';

// FOR FETCHING RECIPE(s)
export const RECIEVE_SINGLE_RECIPE = 'RECIEVE_SINGLE_RECIPE';
export const RECIEVE_ALL_RECIPE = 'RECIEVE_ALL_RECIPE';
export const RECIEVE_TOP_RATED_RECIPE = 'RECIEVE_TOP_RATED_RECIPE';
export const RECIEVE_NEW_RECIPE = 'RECIEVE_NEW_RECIPE';

export const POST_REVIEW = 'POST_REVIEW';

// USER DETAILS
export const RECIEVE_USER_PROFILE = 'RECIEVE_USER_PROFILE';
export const REMOVE_RECIPE_FROM_PROFILE = 'REMOVE_RECIPE_FROM_PROFILE';
export const RECIEVE_UPDATED_RECIPE = 'RECIEVE_UPDATED_RECIPE';
