export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const REMOVE_AUTH_ERROR_MESSAGE = 'REMOVE_AUTH_ERROR_MESSAGE';

// FOR API CALLS
export const SET_FETCHING = 'SET_FETCHING';
// note: doesn't mean its successful just that the api responded
export const UNSET_FETCHING = 'UNSET_FETCHING';

export const RECEIVE_SINGLE_RECIPE = 'RECIEVE_SINGLE_RECIPE';
export const FETCH_SINGLE_RECIPE_ERROR = 'FETCH_SINGLE_RECIPE_ERROR';
export const RESET_SINGLE_RECIPE = 'RESET_SINGLE_RECIPE';

export const RECEIVE_ALL_RECIPE = 'RECEIVE_ALL_RECIPE';
export const RECEIVE_TOP_RATED_RECIPES = 'RECEIVE_TOP_RATED_RECIPES';
export const FETCH_TOP_RECIPES_ERROR = 'FETCH_TOP_RECIPES_ERROR';

export const RECEIVE_PERSONAL_RECIPES = 'RECEIVE_PERSONAL_RECIPES';
export const RECEIVE_FAVORITE_RECIPES = 'RECEIVE_FAVORITE_RECIPES';
export const RECEIVE_NEW_RECIPE = 'RECEIVE_NEW_RECIPE';
export const FETCH_PERSONAL_RECIPES_ERROR = 'FETCH_PERSONAL_RECIPES_ERROR';
export const FETCH_FAVORITE_RECIPES_ERROR = 'FETCH_FAVORITE_RECIPES_ERROR';

export const RECEIVE_RECIPE_REVIEWS = 'RECEIVE_RECIPE_REVIEWS';
export const FETCH_RECIPE_REVIEWS_ERROR = 'FETCH_RECIPE_REVIEWS_ERRORS';
export const POST_REVIEW = 'POST_REVIEW';

// USER DETAILS
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';
export const RECEIVE_UPDATED_RECIPE = 'RECEIVE_UPDATED_RECIPE';
export const RECEIVE_CURRENT_USER_ERROR = 'RECEIVE_CURRENT_USER_ERROR';

// CURRENT USER
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
